from .version_programa_asignatura import ServicioVersionProgramaAsignatura
from .descriptor import ServicioDescriptor
from .semestre import ServicioSemestre
from .configuracion import ServicioConfiguracion
from .roles import ServicioRoles
from .anio_academico import ServicioAnioAcademico
from .plan_de_estudio import ServicioPlanDeEstudio
from .obtener_programas_historial import obtener_programas_historial
