from .version_programa_asignatura import ServicioVersionProgramaAsignatura
from .descriptor import ServicioDescriptor
from .semestre import ServicioSemestre
from .configuracion import ServicioConfiguracion
