# Generated by Django 4.2.4 on 2023-08-14 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('version', models.TextField()),
                ('nombre', models.TextField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.carrera')),
            ],
        ),
        migrations.AddConstraint(
            model_name='plandeestudio',
            constraint=models.CheckConstraint(check=models.Q(('fecha_inicio__lte', models.F('fecha_fin'))), name='backend_plan_de_estudio_fecha_fin_posterior_a_fecha_inicio', violation_error_message='Fecha fin mayor o igual a fecha inicio.'),
        ),
    ]
