# Generated by Django 4.2.4 on 2024-06-02 20:10

import backend.common.funciones_fecha
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("profile_picture", models.URLField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActividadReservada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Actividades Reservadas",
            },
        ),
        migrations.CreateModel(
            name="AnioAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
            ],
            options={
                "verbose_name": "Año académico",
                "verbose_name_plural": "Años académicos",
            },
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("denominacion", models.CharField(max_length=255)),
                (
                    "codigo",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                (
                    "metodologia",
                    models.CharField(
                        choices=[
                            ("P", "Presencial"),
                            ("V", "Virtual"),
                            ("H", "Hibrido"),
                        ],
                        max_length=1,
                    ),
                ),
                ("semanas_dictado", models.PositiveIntegerField()),
                (
                    "semanal_teoria_presencial",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_practica_presencial",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_teorico_practico_presencial",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_lab_presencial",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_teoria_remoto",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_practica_remoto",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_teorico_practico_remoto",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "semanal_lab_remoto",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "horas_evaluacion",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("carga_rtf", models.PositiveIntegerField()),
                (
                    "semestre_dictado",
                    models.CharField(
                        blank=True,
                        choices=[("PS", "Primer Semestre"), ("SS", "Segundo Semestre")],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BloqueCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("coeficiente", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name_plural": "Bloques Curriculares",
            },
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Configuracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            (
                                "IPM",
                                "Días previos al inicio del Semestre para Modificar el Programa",
                            ),
                            (
                                "IPV",
                                "Días previos al inicio del Semestre para Validar el Programa",
                            ),
                            (
                                "IPC",
                                "Días previos al inicio del Semestre para Corregir el Programa",
                            ),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("valor", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Configuraciones",
            },
        ),
        migrations.CreateModel(
            name="Descriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("E", "Eje Transversal"), ("D", "Descriptor")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Descriptores",
            },
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "semestre",
                    models.CharField(
                        choices=[("PS", "Primer Semestre"), ("SS", "Segundo Semestre")],
                        max_length=2,
                    ),
                ),
                (
                    "anio_academico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.anioacademico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionProgramaAsignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("A", "Abierto"),
                            ("P", "Pendiente"),
                            ("AP", "Aprobado"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("contenidos", models.TextField()),
                ("bibliografia", models.TextField()),
                ("recursos", models.TextField()),
                ("evaluacion", models.TextField()),
                ("investigacion_docentes", models.TextField()),
                ("investigacion_estudiantes", models.TextField()),
                ("extension_docentes", models.TextField()),
                ("extension_estudiantes", models.TextField()),
                ("cronograma", models.TextField()),
                ("metodologia_aplicada", models.TextField()),
                ("fundamentacion", models.TextField()),
                ("resultados_de_aprendizaje", models.JSONField()),
                (
                    "creado_en",
                    models.DateTimeField(
                        default=backend.common.funciones_fecha.obtener_fecha_y_hora_actual
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.asignatura",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.semestre",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Versiones de Programa de Asignatura",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("DC", "Director de Carrera"),
                            ("TC", "Titular de Catedra"),
                            ("SA", "Secretario Academico"),
                            ("D", "Docente"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "dedicacion",
                    models.CharField(
                        choices=[("N", "No exclusiva"), ("E", "Exclusiva")],
                        max_length=2,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "asignatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.asignatura",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.carrera",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="ProgramaTieneDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (0, "Nada"),
                            (1, "Bajo / Si"),
                            (2, "Medio"),
                            (3, "Alto"),
                        ]
                    ),
                ),
                (
                    "descriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.descriptor",
                    ),
                ),
                (
                    "version_programa_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.versionprogramaasignatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Descriptores para Programas",
            },
        ),
        migrations.CreateModel(
            name="ProgramaTieneActividadReservada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (0, "Nada"),
                            (1, "Bajo / Si"),
                            (2, "Medio"),
                            (3, "Alto"),
                        ]
                    ),
                ),
                (
                    "actividad_reservada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.actividadreservada",
                    ),
                ),
                (
                    "version_programa_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.versionprogramaasignatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Actividades Reservadas para Programas",
            },
        ),
        migrations.CreateModel(
            name="PlanDeEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=255)),
                (
                    "asignaturas",
                    models.ManyToManyField(
                        related_name="planes_de_estudio", to="backend.asignatura"
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Planes de Estudio",
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("VP", "Version pendiente para correccion")],
                        max_length=2,
                    ),
                ),
                (
                    "creada",
                    models.DateTimeField(
                        default=backend.common.funciones_fecha.obtener_fecha_y_hora_actual
                    ),
                ),
                ("leida", models.DateTimeField(blank=True, null=True)),
                ("mensaje", models.CharField(blank=True, max_length=255, null=True)),
                ("redirecciona", models.URLField(max_length=255)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notificaciones",
            },
        ),
        migrations.CreateModel(
            name="Estandar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.carrera",
                    ),
                ),
                (
                    "descriptores",
                    models.ManyToManyField(
                        blank=True, null=True, to="backend.descriptor"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Estándares",
            },
        ),
        migrations.CreateModel(
            name="Correlativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("R", "Regular"), ("A", "Aprobado")], max_length=1
                    ),
                ),
                (
                    "requisito",
                    models.CharField(
                        choices=[
                            ("asignatura", "Asignatura aprobada o regular"),
                            ("cantidad", "Número de asignaturas aprobadas o regulares"),
                            ("modulo", "Módulo aprobado o regular"),
                        ],
                        max_length=10,
                    ),
                ),
                ("modulo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cantidad_asignaturas",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "asignatura_correlativa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.asignatura",
                    ),
                ),
                (
                    "version_programa_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="backend.versionprogramaasignatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditoriaRevisionDocentes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(
                        default=backend.common.funciones_fecha.obtener_fecha_y_hora_actual
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CN", "Crear nuevo programa de asignatura"),
                            ("E", "Editar programa de asignatura"),
                            ("P", "Presentar programa de asignatura para aprobación"),
                            ("A", "Aprobar programa de asignatura"),
                            ("RU", "Reutilizar úlitmo programa de asignatura"),
                            ("PC", "Pedir cambios en el programa de asignatura"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version_programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.versionprogramaasignatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Auditorias Revisión de Docentes",
            },
        ),
        migrations.CreateModel(
            name="AuditoriaEstadoVersionPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("A", "Aprbado"),
                            ("PC", "Pedir cambios"),
                            ("AD", "Aprobacion Deprecada"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("mensaje_cambios", models.TextField()),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="backend.rol"
                    ),
                ),
                (
                    "version_programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.versionprogramaasignatura",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Auditorias Estado Version Programas",
            },
        ),
        migrations.AddField(
            model_name="asignatura",
            name="bloque_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="backend.bloquecurricular",
            ),
        ),
        migrations.AddConstraint(
            model_name="anioacademico",
            constraint=models.CheckConstraint(
                check=models.Q(("fecha_inicio__lte", models.F("fecha_fin"))),
                name="backend_anio_academico_fecha_fin_posterior_a_fecha_inicio",
                violation_error_message="Fecha fin mayor o igual a fecha inicio.",
            ),
        ),
        migrations.AddField(
            model_name="actividadreservada",
            name="estandar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="backend.estandar"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddConstraint(
            model_name="versionprogramaasignatura",
            constraint=models.UniqueConstraint(
                fields=("asignatura", "semestre"), name="version_semestre_asignatura_ux"
            ),
        ),
        migrations.AddConstraint(
            model_name="semestre",
            constraint=models.CheckConstraint(
                check=models.Q(("fecha_inicio__lte", models.F("fecha_fin"))),
                name="backend_semestre_fecha_fin_posterior_a_fecha_inicio",
                violation_error_message="Fecha fin mayor o igual a fecha inicio.",
            ),
        ),
        migrations.AddConstraint(
            model_name="semestre",
            constraint=models.UniqueConstraint(
                fields=("anio_academico", "semestre"),
                name="backend_semestre_un_semestre_de_tipo_por_anio_academico",
            ),
        ),
        migrations.AddConstraint(
            model_name="plandeestudio",
            constraint=models.CheckConstraint(
                check=models.Q(("fecha_inicio__lte", models.F("fecha_fin"))),
                name="backend_plan_de_estudio_fecha_fin_posterior_a_fecha_inicio",
                violation_error_message="Fecha fin mayor o igual a fecha inicio.",
            ),
        ),
    ]
