# Generated by Django 4.2.4 on 2023-12-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anioacademico",
            options={
                "verbose_name": "Año académico",
                "verbose_name_plural": "Años académicos",
            },
        ),
    ]
