# Generated by Django 4.2.4 on 2023-09-11 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEstadoVersionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('P', 'Pendiente'), ('AP', 'Aprobado')], max_length=2)),
                ('modificado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Auditorias Estado Version Programas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DC', 'Director de Carrera'), ('TC', 'Titular de Catedra'), ('SA', 'Secretario Academico'), ('D', 'Docente')], max_length=2)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.asignatura')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.carrera')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='bloquecurricular',
            options={'verbose_name_plural': 'Bloques Curriculares'},
        ),
        migrations.AlterModelOptions(
            name='cargabloque',
            options={'verbose_name_plural': 'Carga Bloques'},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='descriptor',
            options={'verbose_name_plural': 'Descriptores'},
        ),
        migrations.AlterModelOptions(
            name='estandar',
            options={'verbose_name_plural': 'Estándares'},
        ),
        migrations.AlterModelOptions(
            name='plandeestudio',
            options={'verbose_name_plural': 'Planes de Estudio'},
        ),
        migrations.AlterModelOptions(
            name='programatienedescriptor',
            options={'verbose_name_plural': 'Descriptores para Programas'},
        ),
        migrations.AlterModelOptions(
            name='versionprogramaasignatura',
            options={'verbose_name_plural': 'Versiones de Programa de Asignatura'},
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='resultados_de_aprendizaje',
        ),
        migrations.DeleteModel(
            name='ResultadoDeAprendizaje',
        ),
        migrations.AddField(
            model_name='auditoriaestadoversionprograma',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.rol'),
        ),
        migrations.AddField(
            model_name='auditoriaestadoversionprograma',
            name='version_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.versionprogramaasignatura'),
        ),
        migrations.AddField(
            model_name='versionprogramaasignatura',
            name='resultados_de_aprendizaje',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
