# Generated by Django 4.2.4 on 2023-09-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estandar',
            name='descriptores',
            field=models.ManyToManyField(blank=True, null=True, to='backend.descriptor'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('VP', 'Version pendiente para correccion')], max_length=2),
        ),
        migrations.AlterField(
            model_name='plandeestudio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
