# Generated by Django 4.2.5 on 2024-02-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_anioacademico_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='planes_de_estudio',
            field=models.ManyToManyField(blank=True, related_name='asignaturas_relacionadas', to='backend.plandeestudio'),
        ),
        migrations.AddField(
            model_name='rol',
            name='dedicacion',
            field=models.CharField(choices=[('N', 'No exclusiva'), ('E', 'Exclusiva')], default='N', max_length=2),
            preserve_default=False,
        ),
    ]
