# Generated by Django 4.2.4 on 2024-03-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_versionprogramaasignatura_fundamentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='horas_evaluacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='dedicacion',
            field=models.CharField(choices=[('N', 'No exclusiva'), ('E', 'Exclusiva')], default='N', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plandeestudio',
            name='asignaturas',
            field=models.ManyToManyField(related_name='planes_de_estudio', to='backend.asignatura'),
        ),
    ]
