# Generated by Django 4.2.5 on 2024-02-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_asignatura_planes_de_estudio_rol_dedicacion'),
        ('backend', '0003_versionprogramaasignatura_fundamentacion_and_more'),
    ]

    operations = [
    ]
