# Generated by Django 4.2.4 on 2023-11-16 19:44

import backend.common.funciones_fecha
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_configuracion_nombre_alter_configuracion_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_lab_presencial',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_lab_remoto',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_practica_presencial',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_practica_remoto',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_teoria_presencial',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_teoria_remoto',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_teorico_practico_presencial',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanal_teorico_practico_remoto',
        ),
        migrations.RemoveField(
            model_name='versionprogramaasignatura',
            name='semanas_dictado',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carga_rtf',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_lab_presencial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_lab_remoto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_practica_presencial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_practica_remoto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_teoria_presencial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_teoria_remoto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_teorico_practico_presencial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanal_teorico_practico_remoto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semanas_dictado',
            field=models.PositiveIntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='versionprogramaasignatura',
            name='creado_en',
            field=models.DateTimeField(default=backend.common.funciones_fecha.obtener_fecha_y_hora_actual),
        ),
        migrations.DeleteModel(
            name='CargaBloque',
        ),
    ]
