# Generated by Django 4.2.5 on 2024-02-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_merge_20240226_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='horas_evaluacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
