# Generated by Django 4.2.4 on 2023-11-30 18:57

import backend.common.funciones_fecha
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_versionprogramaasignatura_semanal_lab_presencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='creada',
            field=models.DateTimeField(default=backend.common.funciones_fecha.obtener_fecha_y_hora_actual),
        ),
    ]
