# Generated by Django 4.2.4 on 2024-04-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auditoriarevisiondocentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='profile_picture',
            field=models.URLField(default='http://profilepic.png', max_length=255),
            preserve_default=False,
        ),
    ]
