# Generated by Django 4.2.4 on 2024-04-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_usuario_profile_picture"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="versionprogramaasignatura",
            constraint=models.UniqueConstraint(
                fields=("asignatura", "semestre"), name="version_semestre_asignatura_ux"
            ),
        ),
    ]
