# Generated by Django 4.2.4 on 2024-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_rol_fecha_fin_rol_fecha_inicio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plandeestudio",
            name="version",
        ),
        migrations.AlterField(
            model_name="plandeestudio",
            name="nombre",
            field=models.CharField(),
        ),
    ]
