# Generated by Django 4.2.4 on 2024-06-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_remove_plandeestudio_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plandeestudio",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
