from .asignatura import SerializerAsignatura, SerializerAsignaturaParaSeleccion
from .programas_vigentes import ProgramasVigentesSerializer
from .programa_asignatura import serializer_programa_asignatura
