MENSAJE_FECHAS_INCORRECTAS = "Fecha fin mayor o igual a fecha inicio."
CODIGO_ASIGNATURA_INCORRECTO = "El codigo de la asignatura debe comenzar con '15_', y continuar con tres caracteres en mayuscula."
MENSAJE_EMAIL_NO_PROPORCIONADO = "Email no proporcionado."
MENSAJE_SUPERUSUARIO_ACTIVO = "Superusuario deberia estar activo."
MENSAJE_SUPERUSUARIO = "Superusuario deberia estar marcado como superusuario."
MENSAJE_SUPERUSUARIO_STAFF = "Superusuario deberia ser staff."
