from .carrera import Carrera
from .plan_de_estudio import PlanDeEstudio
from .descriptor import Descriptor
from .estandar import Estandar
from .bloque_curricular import BloqueCurricular
from .asignatura import Asignatura
from .semestre import Semestre
from .configuracion import Configuracion
from .version_programa_asignatura import VersionProgramaAsignatura
from .programa_tiene_descriptor import ProgramaTieneDescriptor
from .correlativa import Correlativa
from .carga_bloque import CargaBloque
from .resultado_de_aprendizaje import ResultadoDeAprendizaje
from .usuario import Usuario
