from .carrera import Carrera
from .plan_de_estudio import PlanDeEstudio
from .descriptor import Descriptor
from .estandar import Estandar
from .bloque_curricular import BloqueCurricular
from .asignatura import Asignatura
from .semestre import Semestre
from .configuracion import Configuracion
from .version_programa_asignatura import VersionProgramaAsignatura
from .programa_tiene_descriptor import ProgramaTieneDescriptor
from .correlativa import Correlativa
from .usuario import Usuario
from .rol import Rol
from .auditoria_estado_version_programa import AuditoriaEstadoVersionPrograma
from .notificacion import Notificacion
from .actividad_reservada import ActividadReservada
from .programa_tiene_actividad_reservada import ProgramaTieneActividadReservada
